// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPin7ePdJqOmI0yVPrtqu7AsrcHlns0HM',
    appId: '1:146786816007:web:d9c4808d5a6e68535c9aa2',
    messagingSenderId: '146786816007',
    projectId: 'seating-charts-dc9f8',
    authDomain: 'seating-charts-dc9f8.firebaseapp.com',
    databaseURL: 'https://seating-charts-dc9f8-default-rtdb.firebaseio.com',
    storageBucket: 'seating-charts-dc9f8.appspot.com',
    measurementId: 'G-EZSV2SH764',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzzxthZpUQXrWSBPwXsGQcz6rK2E8ijNI',
    appId: '1:146786816007:android:643c3478a298d7b35c9aa2',
    messagingSenderId: '146786816007',
    projectId: 'seating-charts-dc9f8',
    databaseURL: 'https://seating-charts-dc9f8-default-rtdb.firebaseio.com',
    storageBucket: 'seating-charts-dc9f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzdiw4Ek9PFBt2O_hvqGv9DEc6wE7Sfo4',
    appId: '1:146786816007:ios:3214979367b7615a5c9aa2',
    messagingSenderId: '146786816007',
    projectId: 'seating-charts-dc9f8',
    databaseURL: 'https://seating-charts-dc9f8-default-rtdb.firebaseio.com',
    storageBucket: 'seating-charts-dc9f8.appspot.com',
    iosClientId: '146786816007-o9ullui8ged821elfh80tqtptedjs54a.apps.googleusercontent.com',
    iosBundleId: 'com.example.t',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzdiw4Ek9PFBt2O_hvqGv9DEc6wE7Sfo4',
    appId: '1:146786816007:ios:bf57a4d4e89133e05c9aa2',
    messagingSenderId: '146786816007',
    projectId: 'seating-charts-dc9f8',
    databaseURL: 'https://seating-charts-dc9f8-default-rtdb.firebaseio.com',
    storageBucket: 'seating-charts-dc9f8.appspot.com',
    iosClientId: '146786816007-hq73drfjrcrck6dbqsp1kcl0db8najb7.apps.googleusercontent.com',
    iosBundleId: 'com.example.t.RunnerTests',
  );
}
